# Generated by Django 4.2 on 2025-06-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0002_remove_myuser_name_alter_myuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(blank=True, max_length=11, verbose_name='telefone'),
        ),
    ]
